server:
  port: 8080
  error:
    include-message: always

spring:

  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: azizairo
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    web-application-type: servlet